---
_select:
  # classifier: [RegularClassifier, ClassifierGridSearch, EvaluateClassifier]
  classifier: null
  # dataset: [KaraOne, FEIS]
  dataset: null
classifier:
  features_select_k_best:
    k: null
    score_func: null
  model_base_dir: null
  models: null
  n_splits: null
  random_state: null
  test_size: null
  trial_size: null
feis:
  epoch_type: null
  features_dir: null
  raw_data_dir: null
  subjects: null
  tasks: null
  tfr_dataset_dir: null
karaone:
  channels: null
  epoch_type: null
  features_dir: null
  filtered_data_dir: null
  length_factor: null
  overlap: null
  raw_data_dir: null
  subjects: null
  tasks: null
  tfr_dataset_dir: null
tfr:
  batch_size: null
  max_epochs: null
  model_base_dir: null
  trial_size: null
utils:
  path: null