---
feis:
  data_dir: null
  features_dir: null
  model_dir: null
karaone:
  features_dir: null
  filtered_data_dir: null
  grid_search: null
  model_dir: null
  raw_data_dir: null
  task: null
  tfr_dataset_dir: null
  trial_size: null
utils:
  path: null