---
feis:
  data_dir: null
  features_dir: null
  model_dir: null
karaone:
  evaluate_only: null
  features_dir: null
  filtered_data_dir: null
  grid_search: null
  model_base_dir: null
  models: null
  raw_data_dir: null
  tasks: null
  tfr_dataset_dir: null
  trial_size: null
utils:
  path: null